sudo: required
language: python
services:
- docker

python:
  - "3.6"
  - "3.7"

install: "pip install -r requirement.txt"

script:
- coverage run task2_unittest.py
- docker image build -t pctovera/helloworld01 .

after_success:
  - bash <(curl -s https://codecov.io/bash)
  #log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #take built images and push to DOcker hub
  - docker push pctovera/helloworld01
  #test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "helloworld"
  env: "Helloworld-env"
  bucket_name: "elasticbeanstalk-us-east-2-839274515579"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
